### ISSUE TITLE
popper appendToBody and remove node ref when hidden

### ISSUE THREAD

**Issue by MrFrankel** [MrFrankel/ngx-popper#72]

**Comment by MrFrankel** [comment]
I have released vs ngx-popper@5.0.0-beta5, it remove it popper-content innerHTML when hidden.

See if that improves performance.

Though I have used it with ngFor with hundreds of elements with no effect on performance

**Comment by jandresampaio** [comment]
Thanks for the update. 

I've been working with this...
Because now you're destroying the poppers when components are destroyed, or when navigating to other route, the following code might break navigation if popperContent is null. 

`   PopperController.prototype.ngOnDestroy = /**
     * @return {?}
     */
    function () {
        this.subscriptions.forEach(function (sub) { return sub.unsubscribe && sub.unsubscribe(); });
        this.subscriptions.length = 0;
        this.clearEventListeners();
        this.clearGlobalEventListeners();
        this.popperContent.ngOnDestroy();
    };`

For instance, I had a bug in the code where I referenced a popper object that was commented out, like 
`           
            <div [popper]="fileInfoTooltip" class="temp-file" style="width: 80px;height: 74px;">
                                    <div title="{{file.Name}}" style="width: 80px;overflow: hidden;max-height: 33px;min-height: 22px;line-height: 12px;padding: 0px 7px;font-size: 10px;margin-top: 11px;">{{file.Name}}</div>
                                    <div style="margin-top:-2px;">
                                        <i class="fa fa-download" (click)="downloadFile(file)" popper="{{'DownloadFile' | translate}}"  style="cursor:pointer;font-size: 14px;color: #666;padding: 10px;"></i>
                                        <i *ngIf="!file.IsMissing" class="fa fa-picture-o" (click)="previewFile(file)" popper="{{'PreviewFile' | translate}}"  style="cursor:pointer;font-size: 14px;color: #666;padding: 10px;"></i>
                                    </div>
                                </div>
               
                                  

`

and then when trying to destroy I got a `ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'ngOnDestroy' of undefined
TypeError: Cannot read property 'ngOnDestroy' of undefined`. 
This breaks the navigation

But seems to work fine, solved some bugs on poppers that would appear clipped otherwise.

**Comment by MrFrankel** [comment]
@jandresampaio thanks, im looking into the best way to remove the content of an element when it is hidden, ill dig deeper into Angular code see whats the best way to go about it/

**Comment by jandresampaio** [comment]
Hi, 

The appendToBody was present 5.0.0-beta5 but not in later versions. Is this expected ? How can I use the appendToBody in newer versions, since this console errors still keep appearing quite often.

Thank you.

**Comment by jandresampaio** [comment]
Hi @MrFrankel , 

Any news on this ?

Thank you.

**Comment by MrFrankel** [comment]
@jandresampaio sorry, I missed this.
Ill look into it, though we use the latest version of this in the product that the company I work for in production and we dont see any instances if the error, are you sure you tried the latest?

**Comment by jandresampaio** [comment]
But appendToBody setting is not supported on latest version, only appendTo. Is appendTo the setting to use with 'body" as parameter ?

**Comment by MrFrankel** [comment]
Yes! or any other element selector you want to use

**Comment by aleksander351** [comment]
@MrFrankel Hi. When using [appendTo]="'body'", the element gets appended to body, but is not destroyed after hiding. Can you confirm?

**Comment by ShivManne** [comment]
I do have the same questions as @aleksander351 . the element is not destroyed on popper hide.  Is this as per design ?
